### ISSUE TITLE
[BUG] Secret Manager 적용 후 로깅 appender를 못 불러옴

### ISSUE THREAD

**Issue by pminsung12** [depromeet/SPOT-server#192]
## 📍 재현 위치

- secret manager 관련 pr #187  배포 후 dev 서버에서 발생

![image](https://github.com/user-attachments/assets/0fd031e1-47c7-430a-9739-21d7f33823b5)

## 📌 상황 설명

- LOKI_URL이 secret manager에 정의되어 있지만 appender에서 불러오지 못하고 있음.
- 로컬에서 확인한 결과 .env로 등록했을 때는 잘 실행됨.
- 따라서 spring 서버가 실행될 때 appender가 생성되는 시점과 secret manager에서 환경변수를 등록하는 시점을 비교해봐야함.
- 합리적 의심으로는 appender이 먼저라 불러오지 못하는 듯함. 

## 🤔 정상 기대값 (선택)

- 정상 실행

**Comment by pminsung12** [comment]
**`해결 방안 1`**

docker run -e 로 서버 실행시킬 때 외부에서 `LOKI_URL` 주입

장점: 간단함.
단점: 기존의 방법을 다시 쓰는 거라 꺼림칙함. 그리고 근복적인 해결책이 아님.

**Comment by pminsung12** [comment]
**`해결 방안 2`**

bootstrap.yml 사용

```yml
        implementation("org.springframework.cloud:spring-cloud-starter-bootstrap:_")
        version.org.springframework.cloud..spring-cloud-starter-bootstrap=3.0.3
```
```
spring:
    cloud:
        bootstrap:
            enabled: true

---
spring:
    config:
        activate:
            on-profile: local
    cloud:
        aws:
            secretsmanager:
                name: spot-local-secrets

---
spring:
    config:
        activate:
            on-profile: dev
    cloud:
        aws:
            secretsmanager:
                name: spot-dev-secrets

---
spring:
    config:
        activate:
            on-profile: prod
    cloud:
        aws:
            secretsmanager:
                name: spot-prod-secrets
```

문제점

secret manager 이름을 받아오지 못함.
스프링 프로필로 넣어놓으면 spot-local-secrets_mixpanel 이런 식으로 자동 생성됨..

![image](https://github.com/user-attachments/assets/06c20887-48f2-4bbb-bb33-27b6941bedd7)
